### ISSUE TITLE
[Bug] No results shown when searching for multiple words

### ISSUE THREAD

**Issue by pidgeon777** [Verf/telescope-everything.nvim#1]
If I search for `worda wordb`, no results are shown.

But if I search for those words by command line through the `es` executable, results are shown.

**Comment by Verf** [comment]
> If I search for `worda wordb`, no results are shown.
> 
> But if I search for those words by command line through the `es` executable, results are shown.

this plugin directly uses the output of es, please check whether the config is the same as es.

**Comment by deltoss** [comment]
It's an issue with the way `es` approaches their search syntax in their CLI.
I.E: If I use `es` directly to find a file "profile" with the filename ".ps1" extension, this works:

```powershell
es profile .ps1
es file: profile.ps1
```

Notice there's no quotes? Because that's how the `es` CLI works. It'd interpret the search query directly so it doesn't need quotes. Only need quotes to escape spaces. (See Everything Docs on [searching](https://www.voidtools.com/support/everything/searching/)) The plugin or telescope is basically calling es like so:

```powershell
es "profile .ps1"
es "file: profile.ps1"
```

Which is a literal search to find a file called "profile .ps1" or "file: profile.ps1", which would give no results. This means you'd lose all the capabilities of es search syntax.

~~The problem is I can't figure out how to adjust the code to pass the prompt as-is without escaping it.~~

**Edit:** Fixed on my fork. Raised a PR.
